version: '3.8'
services:
  django:
    build:
      context: ./
    container_name: django
    ports:
      - "8000:8000"

    environment:
      - HOST=postgres
      - REDIS=redis
    command: sh -c "python3 manage.py migrate && python3 manage.py makemigrations && python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    container_name: redis

  postgres:
    image: postgres:alpine3.19
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1377
      POSTGRES_DB: fanap
      TZ: 'Asia/Tehran'

    volumes:
      - /custom/mount:/var/lib/postgresql/data
