name: Django Testing and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: fanap
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1377

      redis:
        image: redis:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirments.txt

    - name: Apply database migrations
      run: |
        python manage.py migrate
        python manage.py makemigrations 

    - name: Run tests
      run: |
        python manage.py test

  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install flake8
      run: pip install flake8

    - name: Run flake8
      run: |
        flake8 .
